MODEL:
  name: "MAESTER"
  img_size: 80
  patch_size: 5
  embed: 768 # 192
  embed_dim: 768 # 192
  depth: 12 # 14
  num_heads: 12 # 1
  decoder_embed_dim: 512 # 128
  decoder_depth: 8 # 7
  decoder_num_heads: 16 # 8
  mlp_ratio: 4 # 2.0
  mask_ratio: 0.5
  pos_encode_w: 1 # 0.08
  central_patch: 4
DATASET:
  name: "MyBetaSegDataset2D"
  path_list:
    # - "/mnt/embl/scratch/hellgoth/data/chlamy_MAESTER/240229_cw15-wtnew-wtold_interphase_nhs-tub-cetn-dna_cf_00_tensor"
    - "/scratch/hellgoth/data/chlamy_MAESTER/240229_cw15-wtnew-wtold_interphase_nhs-tub-cetn-dna_cf_00_tensor_single"
  pad: 4
  aug: "betaaug2D"
  num_workers: 8
  batch_size: 32
  vol_size: 80
  patch_size: 5
ENGINE:
  name: "my_train_engine"
  epoch: 2800
OPTIM:
  name: "adamw"
  lr: 1.5e-4
  reg_w: 1.0e-5
